highcampers/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

highcampers/blueprints/user/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    url_for,
    render_template)
from flask_login import login_required, logout_user, login_user, current_user
from lib.safe_next_url import safe_next_url
from highcampers.blueprints.user.decorators import anonymous_required

from highcampers.blueprints.user.forms import LoginForm, SignupForm, \
    UpdateCredentialsForm, BeginPasswordReset, PasswordResetForm, UpdatePasswordForm
from highcampers.blueprints.user.models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('This account has been disabled.', 'error')

        else:
            flash('Identity or password is incorrect', 'error')

    return render_template('user/login.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):

            email_verification = u.send_email_verification(u.email)
            from highcampers.blueprints.user.tasks import deliver_welcome_email
            deliver_welcome_email.delay(request.form.get('email'),
                                        current_user.username)

            flash('Complete your registration by confirming your email address', 'warning')
            return redirect(url_for('user.settings'))

    return render_template('user/signup.html', form=form)


@user.route('/email-verification')
def email_verification():
    u = User.deserialize_token(request.args.get('confirmation_token'))

    if u is None:
        flash('Your email confirmation token has expired or tampered with.',
              'error')
        return redirect(url_for('user.begin_password_reset'))

    if login_user(u):
        u.active = True
        u.save()
        flash('Your account is now verified.', 'success')

        return redirect(url_for('user.settings'))


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = UpdateCredentialsForm(current_user, uid=current_user.id)

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.email = request.form.get('email')
        current_user.fullname = request.form.get('fullname', '')

        current_user.save()
        flash('Your profile settings have been updated', 'success')

        return redirect(url_for('user.settings'))

    return render_template('user/settings.html', form=form)


@user.route('/settings/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePasswordForm(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()
        flash('Your password has been updated', 'success')

        return redirect(url_for('user.settings'))

    return render_template('user/update_password.html', form=form)


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordReset()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('page.home'))

highcampers/templates/layouts/app.html
{% extends 'layouts/base.html' %}
{% block header %}
<nav>
   <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('page.home') }}">
{#            <img src="{{ url_for('static', filename='images/highcampers.png') }}"#}
{#                 class="img-responsive d-inline-block align-top"#}
{#                 width="30" height="30"#}
{#                 style="margin: 0.5em 0 0 1em;"#}
{#                 title="Highcampers" alt="Highcampers"/>#}
                    <svg style="margin-top: 0.9em;" width="136px" height="26px" viewBox="0 0 136 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <!-- Generator: Sketch 42 (36781) - http://www.bohemiancoding.com/sketch -->
                    <title>logo</title>
                    <desc>Created with Sketch.</desc>
                    <defs></defs>
                    <g id="Exploration" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="product-selection-1-copy-20" transform="translate(-129.000000, -67.000000)">
                    <g id="Group" transform="translate(114.000000, 55.000000)">
                    <g id="logo" transform="translate(15.000000, 12.000000)">
                    <text id="HIGHC" opacity="0.800000012" font-family="ArcherPro-Bold, ArcherPro" font-size="17.6" font-weight="bold" letter-spacing="0.255999994" fill="#000000">
                        <tspan x="0" y="19.6585366">HIGHC</tspan>
                    </text>
                    <text id="MPERS" opacity="0.800000012" font-family="ArcherPro-Bold, ArcherPro" font-size="17.6" font-weight="bold" letter-spacing="0.255999994" fill="#000000">
                        <tspan x="79.5714286" y="19.6585366">MPERS</tspan>
                    </text>
                    <path d="M68.6470556,25.8092526 C68.4206715,20.3028635 69.2829488,20.8527884 74.9622698,15.3223971 C80.6415909,9.79200568 75.681624,4.49206628 75.4994161,4.46502577 C75.7496462,8.0200929 73.9769411,9.07436885 74.0176016,8.92898815 C75.755302,1.5868828 70.5558051,0 70.5558051,0 C70.5558051,0 72.8488115,2.67451621 65.4497779,8.202035 C58.0507443,13.7295538 61.2254819,16.9660183 61.2254819,16.9660183 C61.3307074,16.876153 67.4600501,10.658081 73.6224612,11.2060115 C71.6337664,11.7980163 70.0001629,13.0704393 69.9260263,13.1748035 C62.8376516,19.8955848 68.7635341,25.9964094 68.7635341,25.9964094" id="Path-10" fill="#F15A53"></path>
                </g>
            </g>
        </g>
    </g>
</svg>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
                <ul class="nav navbar-nav navbar-right">
               {% if current_user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Session</li>
                    <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
                  </ul>
                </li>
              {% else %}
                <li><a href="{{ url_for('user.login') }}">Log in</a></li>
                <li><a href="{{ url_for('user.signup') }}">Sign up</a></li>
              {% endif %}
            </ul>
        </div>
      </div>
    </nav>
  </nav>
{% endblock %}

{% block footer %}
    <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
    <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
    <li><a href="{{ url_for('contact.index') }}">Contact Us</a></li>
{% endblock %}

highcampers/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="Aswin Ranganathan">

    <title>{% block title %}{% endblock %}</title>

    <link rel="icon"
          href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='styles/main.css') }}">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">

    <style>
    @import url('https://fonts.googleapis.com/css?family=Heebo');
    </style>

    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>

  </head>

  <body>
  {% block header %}{% endblock %}


  <main class="container">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
  </main>
  <footer class="footer" style="border-top: none">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Highcampers &copy; 2017</li>
            {% block footer %}{% endblock %}
        </ul>
      </div>
    </footer>



  </body>

  <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>

</html>

highcampers/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}



{% endblock %}

{% block footer %}
    <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
    <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
    <li><a href="{{ url_for('contact.index') }}">Contact Us</a></li>
{% endblock %}