highcampers/blueprints/user/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    url_for,
    render_template)
from flask_login import login_required, logout_user, login_user, current_user
from lib.safe_next_url import safe_next_url
from highcampers.blueprints.user.decorators import anonymous_required

from highcampers.blueprints.user.forms import LoginForm, SignupForm, \
    UpdateCredentialsForm, BeginPasswordReset, PasswordResetForm, UpdatePasswordForm
from highcampers.blueprints.user.models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('This account has been disabled.', 'error')

        else:
            flash('Identity or password is incorrect', 'error')

    return render_template('user/login.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):

            email_verification = u.send_email_verification(u.email)
            from highcampers.blueprints.user.tasks import deliver_welcome_email
            deliver_welcome_email.delay(request.form.get('email'),
                                        current_user.username)

            flash('Complete your registration by confirming your email address', 'warning')
            return redirect(url_for('user.settings'))

    return render_template('user/signup.html', form=form)


@user.route('/email-verification')
def email_verification():
    u = User.deserialize_token(request.args.get('confirmation_token'))

    if u is None:
        flash('Your email confirmation token has expired or tampered with.',
              'error')
        return redirect(url_for('user.begin_password_reset'))

    if login_user(u):
        u.active = True
        u.save()
        flash('Your account is now verified.', 'success')

        return redirect(url_for('user.settings'))


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = UpdateCredentialsForm(current_user, uid=current_user.id)

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.email = request.form.get('email')
        current_user.fullname = request.form.get('fullname', '')

        current_user.save()
        flash('Your profile settings have been updated', 'success')

        return redirect(url_for('user.settings'))

    return render_template('user/settings.html', form=form)


@user.route('/settings/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePasswordForm(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()
        flash('Your password has been updated', 'success')

        return redirect(url_for('user.settings'))

    return render_template('user/update_password.html', form=form)


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordReset()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('page.home'))

highcampers/blueprints/user/templates/user/begin_password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Reset your password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2 well">
      {% call f.form_tag('user.begin_password_reset') %}
        <legend>Reset your password</legend>
        <p class="small help-block sm-margin-bottom">
          We'll send you an email to reset your password.
        </p>
        {% call f.form_group(form.identity, css_class='',
                             autofocus='autofocus',
                             placeholder='Username or Email') %}
        {% endcall %}
        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
                class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>


{% endblock %}

highcampers/blueprints/user/templates/user/login.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Login{% endblock %}
{% block meta_description %}Login into highcampers and explore the world of travellers{% endblock %}

{% block body %}
<div class="login-image"></div>
  <div class="row">
    <div class="col-md-5 panel">
      {% call f.form_tag('user.login') %}
        <legend>Welcome Back</legend>

        {% call f.form_group(form.identity, css_class='',
                             placeholder='Username or Email') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='',
                             placeholder='Enter password') %}
        {% endcall %}

        <button type="submit" class="btn btn-primary">Submit</button>
      {% endcall %}
      <div class="text-center md-margin-top">
        <a href="{{ url_for('user.begin_password_reset') }}" class="text-muted">
          Forgot your password?
        </a>
      </div>

    </div>

  </div>
{% endblock %}

highcampers/blueprints/user/templates/user/password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Enter a new password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.password_reset') %}
        <legend>Enter a new password</legend>

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

highcampers/blueprints/user/templates/user/settings.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Account Settings{% endblock %}
{% block meta_description %}Sign up with highcampers and explore the world of travellers{% endblock %}


{% block body %}
{#    <p>{{ current_user.username }}</p>#}
{#    <p>{{ current_user.password }}</p>#}
{#    <p>{{ current_user.sign_in_count }}</p>#}
{#    <p>{{ current_user.role }}</p>#}
    <div id='settings-selection' class="row">
        <div class="col-md-3 vertical-tabs">
             <ul class="nav nav-tabs">
                  <li class="nav-item active"><a href="#profile-settings"
                                        data-toggle="tab"><i style="padding: 0 10px 0 2px;"
                                                        class="fa fa-user"></i>Profile</a></li>
                  <li class="nav-item"><a href="#billing-settings"
                                          data-toggle="tab"><i style="padding-right: 8px;"
                                                        class="fa fa-credit-card"></i>Billing</a></li>
                  <li class="nav-item"><a href="#preferences-settings"
                                          data-toggle="tab"><i style="padding: 0 10px 0 2px;"
                                                        class="fa fa-cog"></i>Preferences</a></li>
             </ul>
        </div>
        <div class="panel col-md-9 tab-content">
            <div id="profile-settings"
                 class="tab-pane active">
                {% call f.form_tag('user.settings') %}
                <legend>Update Settings</legend>
                {% call f.form_group(form.fullname, css_class='',
                                     autofocus='autofocus',
                                     placeholder='Your Full Name') %}
                {% endcall %}
                {% call f.form_group(form.username, css_class='',
                                     placeholder='Enter your email address') %}
                {% endcall %}
                {% call f.form_group(form.email, css_class='',
                                     placeholder='Enter your email address') %}
                {% endcall %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ url_for('user.update_password') }}"
                   class="btn btn-default">Change Password</a>
                {% endcall %}
            </div>
            <div id="billing-settings" class="tab-pane">
                <h1>Billing Section</h1>
            </div>
            <div id="preferences-settings" class="tab-pane">
                <h1>Preferences</h1>
            </div>
        </div>
    </div>

    <script>
{#    $(document).ready(function() {#}
{#        $(".tabs-menu a").click(function(event) {#}
{#            event.preventDefault();#}
{#            $(this).parent().addClass("active");#}
{#            $(this).parent().siblings().removeClass("active");#}
{#            var tab = $(this).attr("href");#}
{#            $(".panel-tab-contentab-content").not(tab).css("display", "none");#}
{#            $(tab).fadeIn();#}
{#        });#}
{#    });#}
    </script>

{% endblock %}

highcampers/blueprints/user/templates/user/signup.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign Up for a new account{% endblock %}
{% block meta_description %}Sign up with highcampers and explore the world of travellers{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2 well">
      {% call f.form_tag('user.signup') %}
        <legend>Sign up</legend>
        {% call f.form_group(form.username, css_class='',
                             autofocus='autofocus',
                             placeholder='Pick a username') %}
        {% endcall %}
        {% call f.form_group(form.email, css_class='',
                             autofocus='autofocus',
                             placeholder='Enter your email address') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='',
                             placeholder='Create a password') %}
        {% endcall %}
        <p>By signing up, you agree to our <a href="#">Terms</a> and that you have read our <a href="#">Privacy Policy</a> and <a href="#">Content Policy.</a></p>
        <button type="submit" class="btn btn-primary">Register</button>
      {% endcall %}
    </div>
  </div>
{% endblock %}

highcampers/blueprints/user/templates/user/update_password.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Update Password{% endblock %}
{% block meta_description %}Update your password{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-8 col-md-offset-2 well">
      {% call f.form_tag('user.update_password') %}
        <legend>Update your password</legend>
        {% call f.form_group(form.current_password, css_class='',
                             autofocus='autofocus',
                             placeholder='Current Password') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='',
                             autofocus='autofocus',
                             placeholder='Enter a new Password') %}
        {% endcall %}
        <button type="submit" class="btn btn-primary">Update Password</button>
          <a href="{{ url_for('user.settings') }}"
                   class="btn btn-default">Cancel</a>
      {% endcall %}
    </div>
  </div>
{% endblock %}