highcampers/blueprints/admin/models.py
from sqlalchemy import func

from highcampers.blueprints.user.models import User, db


class Dashboard(object):
    @classmethod
    def group_and_count_users(cls):
        '''
        
        Perform group and count for the users
        
        :return: dict 
        '''
        return Dashboard._group_and_count(User, User.role)

    @classmethod
    def _group_and_count(cls, model, field):
        '''
        Group results for a specific model and field
        
        :param model: Name of the Model
        :type model: SQLAlchemy Model
        :param field: Name of the field to group on
        :type field: SQLAlchemy Field
        :return: 
        '''

        count = func.count(field)
        query = db.session.query(count, field).group_by(field).all()

        results = {
            'query': query,
            'total': model.query.count()
        }

        return results

highcampers/blueprints/admin/__init__.py
from highcampers.blueprints.admin.views import admin

highcampers/blueprints/admin/views.py
from flask import (
    Blueprint,
    render_template)
from flask_login import login_required
from highcampers.blueprints.admin.models import Dashboard
from highcampers.blueprints.user.decorators import role_required

admin = Blueprint('admin', __name__, template_folder='templates', url_prefix='/admin')


@admin.before_request
@login_required
@role_required('admin')
def before_request():
    """Protect all of the admin endpoints  """
    pass


@admin.route('')
def dashboard():
    group_and_count_users = Dashboard.group_and_count_users()

    return render_template('page/dashboard.html', group_and_count_users=group_and_count_users)

@admin.route('/users')
def users():
    pass

highcampers/blueprints/admin/templates/page/dashboard.html
{% extends 'layouts/app.html' %}

{% block title %}Admin - Dashboard{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <a href="{{ url_for('admin.users') }}">Users</a>
          <span class="pull-right text-muted">
            {{ group_and_count_users.total }}
          </span>
        </div>
        <div class="panel-body">
          {% for item in group_and_count_users.query %}
            {% set percent = ((item[0] / group_and_count_users.total) * 100) | round %}
            <h5>
              {{ item[1] | title }}
              <span class="text-muted">({{ item[0] }})</span>
            </h5>
            <div class="progress">
              <div class="progress-bar" role="progressbar"
                   aria-valuenow="{{ percent }}" aria-valuemin="0"
                   aria-valuemax="100" style="width: {{ percent }}%;">
                {{ percent }}%
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}